name: Deploy

on:
  pull_request:
  push:
  repository_dispatch:

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm install
      - name: Lint with ESLint
        run: npm run lint
   #   - name: Format with Prettier
   #     run: npm run prettier
      - name: Test with Jest
        run: npm run test
      - name: Build
        run: npm run build
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIA4T54UIRVAA4HE7MR
          aws-secret-access-key: 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
          aws-region: us-east-2
      - name: Get EC2 instance public IP address
        run: aws ec2 describe-instances --filters "Name=tag:Name,Values=my-ec2-instance" --query "Reservations[*].Instances[*].PublicIpAddress" --output text
      - name: Add SSH key
        run: eval "$(ssh-agent -s)" && /usr/bin/ssh-add <(echo "${{ secrets.SSH_PRIVATE_KEY }}")
      - name: Add SSH key
        run: ssh-add <(echo "${{ secrets.SSH_PRIVATE_KEY }}")
      - name: Connect to EC2 instance
        run: ssh -o StrictHostKeyChecking=no ec2-user@ec2-18-191-191-38.us-east-2.compute.amazonaws.com
      - name: Deploy to EC2 instance
        run: |
          # Build and deploy your service on the EC2 instance
          ...
