name: Deploy

on:
  pull_request:
  push:
  repository_dispatch:
jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: npm cache cleaning
        run: npm cache clean --force
      - name: dependency installation
        run: npm install
      - name: Linter
        run: npm run lint
      - name: Formatter
        run: npm run prettier
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Build Docker image
        run: docker build -t my-image .
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image
        run: docker push my-image
