name: Deploy

on:
  pull_request:
  push:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Linter
        run: npm run lint
      - name: Formatter
        run: npm run prettier
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Build Docker image
        run: docker build -t my-image .
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image
        run: docker push my-image
